apiVersion: integration.datadog.upbound.io/v1alpha1
kind: AWSLambdaARN
metadata:
  annotations:
    meta.upbound.io/example-id: integration/v1alpha1/awslambdaarn
  labels:
    testing.upbound.io/example-name: main_collector
  name: main-collector
spec:
  forProvider:
    accountId: "1234567890"
    lambdaArn: arn:aws:lambda:us-east-1:1234567890:function:datadog-forwarder-Forwarder
