apiVersion: integration.datadog.upbound.io/v1alpha1
kind: ConfluentAccount
metadata:
  annotations:
    meta.upbound.io/example-id: integration/v1alpha1/confluentaccount
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    apiKey: TESTAPIKEY123
    apiSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    tags:
    - mytag
    - mytag2:myvalue
