apiVersion: integration.datadog.upbound.io/v1alpha1
kind: ConfluentResource
metadata:
  annotations:
    meta.upbound.io/example-id: integration/v1alpha1/confluentresource
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    accountId: ${datadog_integration_confluent_account.foo.id}
    resourceId: "123456"
    resourceType: kafka
    tags:
    - mytag
    - mytag2:myvalue

---

apiVersion: integration.datadog.upbound.io/v1alpha1
kind: ConfluentAccount
metadata:
  annotations:
    meta.upbound.io/example-id: integration.datadog/v1alpha1/confluentresource
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    apiKey: TESTAPIKEY123
    apiSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    tags:
    - mytag
    - mytag2:myvalue
