apiVersion: integration.datadog.upbound.io/v1alpha1
kind: Pagerduty
metadata:
  annotations:
    meta.upbound.io/example-id: integration/v1alpha1/pagerduty
  labels:
    testing.upbound.io/example-name: pd
  name: pd
spec:
  forProvider:
    apiTokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    schedules:
    - https://ddog.pagerduty.com/schedules/X123VF
    - https://ddog.pagerduty.com/schedules/X321XX
    subdomain: ddog

---

apiVersion: integration.datadog.upbound.io/v1alpha1
kind: PagerdutyServiceObject
metadata:
  annotations:
    meta.upbound.io/example-id: integration.datadog/v1alpha1/pagerduty
  labels:
    testing.upbound.io/example-name: testing_bar
  name: testing-bar
spec:
  forProvider:
    serviceKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    serviceName: testing_bar

---

apiVersion: integration.datadog.upbound.io/v1alpha1
kind: PagerdutyServiceObject
metadata:
  annotations:
    meta.upbound.io/example-id: integration.datadog/v1alpha1/pagerduty
  labels:
    testing.upbound.io/example-name: testing_foo
  name: testing-foo
spec:
  forProvider:
    serviceKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    serviceName: testing_foo
