apiVersion: datadog.upbound.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/serviceaccount
  labels:
    testing.upbound.io/example-name: bar
  name: bar
spec:
  forProvider:
    email: new@example.com
    name: Service Account Bar
    roles:
    - ${data.datadog_role.ro_role.id}
