apiVersion: datadog.upbound.io/v1alpha1
kind: MonitorConfigPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: monitor/v1alpha1/configpolicy
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    policyType: tag
    tagPolicy:
    - tagKey: env
      tagKeyRequired: false
      validTagValues:
      - staging
      - prod
