apiVersion: datadog.upbound.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: datadog/v1alpha1/serviceaccount
  labels:
    testing.upbound.io/example-name: foobar
  name: foobar
spec:
  forProvider:
    email: foobar@example.com
    roles:
      - "a151c436-d6aa-11ee-b30b-da7ad0900002"
