apiVersion: apm.datadog.upbound.io/v1alpha1
kind: RetentionFilter
metadata:
  annotations:
    meta.upbound.io/example-id: apm/v1alpha1/retentionfilter
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    enabled: false
    filter:
    - query: '*'
    filterType: spans-sampling-processor
    name: Sample order
    rate: "1.0"
